name: databasetest
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.3.2
  intl: ^0.18.1
  form_field_validator: ^1.1.0
  reorderable_grid_view: ^2.2.6
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.3
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  min_id: ^1.1.0
  json_annotation: ^4.8.1
  flutter_rating_bar: ^4.0.1
  sliding_up_panel: ^2.0.0+1
dev_dependencies:

  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    

  fonts:
    - family: MitrLight
      fonts:
        - asset: assets/fonts/Mitr-Light.ttf
                  
    - family: Mitr
      fonts:
        - asset: assets/fonts/Mitr-Regular.ttf
    - family: MitrBold
      fonts:        
        - asset: assets/fonts/Mitr-Bold.ttf
    - family: PinyonScript
      fonts:        
        - asset: assets/fonts/PinyonScript-Regular.ttf